; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ~/.platformio/boards
platforms_dir = ~/.platformio/platforms

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
build_flags = 
	-DBOARD_TEENSY40
	-Isrc/teensy40
build_src_filter = 
	+<*.cpp>
	+<teensy40/>
	-<esp32/>
	-<esp32_*>
lib_deps = 
	qwety/SparkFun LIS331 Accelerometers@^1.0.1
	fastled/FastLED@^3.10.3

[env:esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_flags = 
	-DBOARD_ESP32C3
	-Isrc/esp32
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = 
	+<*.cpp>
	+<esp32/>
	-<teensy40/>
	-<esp32_*>
lib_deps = 
	qwety/SparkFun LIS331 Accelerometers@^1.0.1
	fastled/FastLED@^3.10.3
monitor_speed = 115200
platform_packages =
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = 
	-DBOARD_ESP32C3
	-Isrc/esp32
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = 
	+<*.cpp>
	+<esp32/>
	-<teensy40/>
	-<esp32_*>
lib_deps = 
	qwety/SparkFun LIS331 Accelerometers@^1.0.1
	fastled/FastLED@^3.10.3
monitor_speed = 115200
platform_packages =
    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
; upload_port = /dev/cu.usbmodem14201